apiVersion: v1
kind: Service
metadata:
  #Name and label our service
  name: blogwrite-app
  labels:
    app: blogwrite-app
spec:
  # Define type 
  type: NodePort
  selector:
    app: blogwrite-app
  ports:
  - protocol: TCP
    port: 8081
