# Deployment is something new, so we use new version
apiVersion: apps/v1
kind: Deployment
metadata:
  #Give name and label to deployment
  name: kworld-deployment
  labels:
    app: kworld
spec:
  #Describe replica set here
  replicas: 3
  #Make it wait for 10 seconds when new pod is activated before going into next pod(Useful for update)
  minReadySeconds: 10
  strategy:
    type: RollingUpdate
    rollingUpdate:
      # Tell kubernetes to take 1 pod at the time
      maxUnavailable: 1
      # Dont have more than 1 extra pod in a given time
      maxSurge: 1
  selector:
    matchLabels:
      #Make replica set load balance pod with label of app=nginx-hello 
      app: kworld-app
  template:
    metadata:
      labels:
        # Set label value to pods:app=nginx-hello
        app: kworld-app
    spec:
      containers:
      - name: kworld-app
        image: kworld
        imagePullPolicy: Never
        ports:
        - containerPort: 3000