# Deployment is something new, so we use new version
apiVersion: apps/v1
kind: Deployment
metadata:
  #Give name and label to deployment
  name: world-deployment
  labels:
    app: world
spec:
  #Describe replica set here
  replicas: 3
  #Make it wait for 10 seconds when new pod is activated before going into next pod(Useful for update)
  minReadySeconds: 10
  strategy:
    type: RollingUpdate
    rollingUpdate:
      # Tell kubernetes to take 1 pod at the time
      maxUnavailable: 1
      # Dont have more than 1 extra pod in a given time
      maxSurge: 1
  selector:
    matchLabels:
      #Make replica set load balance pod with label of app=world-app
      app: world-app
  template:
    metadata:
      labels:
        # Set label value to pods:app=world-app
        app: world-app
    spec:
      containers:
      - name: world-app
        image: world
        imagePullPolicy: Never
        ports:
        - containerPort: 3000

--- 

apiVersion: v1
kind: Service
metadata:
  #Name and label our service
  name: world-app
  labels:
    app: world-app
spec:
  # Define type 
  type: NodePort
  selector:
    #Select pods which has label world-app
    app: world-app
  ports:
  - protocol: TCP
    port: 3000
